"""Regenerate lib/art.ts from whatever is in public/art.

Artwork arrives from two places — 누끼.zip via prepare-assets.py and the design
deck via prepare-scenes.py — so the manifest is built by scanning the folder
rather than by either script, and both can run in any order.

usage:
    python scripts/build-manifest.py

Requires: pillow
"""
import sys, os
sys.stdout.reconfigure(encoding='utf-8')
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'public', 'art')
OUT = os.path.join(ROOT, 'lib', 'art.ts')

files = sorted(f for f in os.listdir(SRC) if f.endswith('.webp'))
if not files:
    sys.exit('public/art is empty — run scripts/prepare-assets.py first.')

rows = []
for f in files:
    with Image.open(os.path.join(SRC, f)) as im:
        rows.append((f[:-5], im.width, im.height))

lines = [
    '// Generated by scripts/build-manifest.py - do not edit by hand.',
    '// Sources: 누끼.zip (prepare-assets.py) + 똑똑 2차.pdf (prepare-scenes.py).',
    '',
    'export const art = {',
]
for stem, w, h in rows:
    lines.append(f"  {stem.replace('-', '_')}: {{ src: '/art/{stem}.webp', width: {w}, height: {h} }},")
lines += ['} as const;', '', 'export type ArtKey = keyof typeof art;', '']

with open(OUT, 'w', encoding='utf-8') as fh:
    fh.write('\n'.join(lines))

print(f'{len(rows)} artworks -> {os.path.relpath(OUT, ROOT)}')
